### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by HassanAmed** [Mugichoko445/Fast-Digital-Image-Inpainting#2]
I tried to run this code but it shows some unhandled exception can you address the issue ASAP  
"Unhandled exception at 0x00007FF84A214008 in AI Project.exe: Microsoft C++ exception: cv::Exception at memory location 0x000000306D74EF10."
Exception is pointed at ln 19 

> cv::imshow("src", src);

Console window says this message
> OpenCV(3.4.1)

 Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file C:\build\master_winpack-build-win64-vc14\opencv\modules\highgui\src\window.cpp, line 356

**Comment by Mugichoko445** [comment]
The error says "(size.width>0 && size.height>0)" and this seems to mean there is no image data to be displayed. I guess the code failed to load your input image. Please check the path you input (see line 8 in "Main.cpp")

**Comment by HassanAmed** [comment]
Yes that was the problem but I got that fixed.
Thanks anyway for your concern.
