### ISSUE TITLE
Performace

### ISSUE THREAD

**Issue by Po-Ting-lin** [Mugichoko445/Fast-Digital-Image-Inpainting#5]
Hi, 
Thanks for your contribution, useful code.
But I am curious about the performance of this algorithm.
Could you provide the elapsed time @500 iterations, the test image.

Lin

**Comment by Mugichoko445** [comment]
Hi, thank you for your question.
The performance depends on the number of mask pixels of your image and your machine. Since it's an open source, you can always test it by yourself ;)

**Comment by camilleg** [comment]
This issue should be closed as won't fix.
